### ISSUE TITLE
Error on open file

### ISSUE THREAD

**Issue by igorvar** [vijaykirann/SiebLogScanner#1]
Good idea, but presents some bugs.
Impossible to open file from siebel original folder - file need be copied to other folder
I have error in file Form1.cs row 149:
str15 = str15.Substring(0, str15.IndexOf(" "));
updated to 
if (str15.IndexOf(" ") >= 0) str15 = str15.Substring(0, str15.IndexOf(" "));
Thanks for your work and good luck.

**Comment by vijaykirann** [comment]
Sure thanks mate.. Will work and fix it

**Comment by vijaykirann** [comment]
Commited the code added BS execution and few UI fixes
